apiVersion: argoproj.io/v1alpha1
   kind: Application
   metadata:
     name: nginx-proxy
     namespace: argocd
   spec:
     source:
       repoURL: 'git@github.com:AML-1204pythonprogramming/argocd.git'
       path: nginx
       targetRevision: HEAD
     destination:
       server: https://kubernetes.default.svc
       namespace: default
